### PR TITLE
Fix the envKey in Config.java

### LINKED ISSUE #10: There may be a mistake usage of `replaceAll()` for the variable `envKey` .
There may be a mistake usage of `replaceAll()` for the variable `envKey` .

### PR DESCRIPTION
**Pull request by iskey**
fix #10

### CODE REVIEW

**Comment by fpapon** [comment]
@iskey can you add a test to validate please?

**Comment by jbonofre** [comment]
Thanks, let me take a look.

**Comment by iskey** [comment]
> @iskey can you add a test to validate please?

ok, let me do some tests.

**Comment by fpapon** [comment]
> Better to do a mock test. Post two snapshots for contrast for now:
> 
> from image
> 
> to image

Sounds good!

**Comment by rmannibucau** [comment]
If possible try avoiding a mock please, it is like not testing at all at the end.
Using surefire you can force some env var so it is then easy to check it is used or not cases IMHO.

**Comment by jbonofre** [comment]
I think we don't need a mock for the test. We can directly test the `ConfigService` and setting a system property to test.
Actually, I think for this kind of "simple" bug, we can just move forward without test.

**Comment by jbonofre** [comment]
If no objection, I will merge this PR.

**Comment by rmannibucau** [comment]
Guess the regex should be extracted if config service is used at runtime instead of recompiled each time.

**Comment by jbonofre** [comment]
@rmannibucau good point, we can have the Pattern compile as static.

**Comment by fpapon** [comment]
@jbonofre agree, no mock is needed, go for merge.

**Review by fpapon — APPROVED** [review]

**Comment by iskey** [comment]
Agree, no mock here. Actually, it is hard to mock without extracting the `getEnv` as another method.
Let me make the pattern static.

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
